baseurl = "https://beartek.pw/eiwos/docs"
languageCode = "es-es"
title = "EIWOS Docs"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
DefaultContentLanguage = "es"

[params]
	# General information
	description = "Documetacion del estandar eiwos"
	copyright = "This work is licensed under the Creative Commons Reconocimiento 4.0 Internacional License. To view a copy of this license, visit http://creativecommons.org/licenses/by/4.0/."

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/eiwos/docs/"

	version = "0.7.0"
	logo = "/static/logo.svg"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	authors = [ "endes123321",  ]

	contributors = "Contribuidores a esta documentacion"
	next = "Siguiente"
	prev = "Anterior"
	ongithub = "Ver esta pagina en github"

	[params.palette]
    	primary = "blue"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = "@endes3000"
	github  = "endes123321"
	email   = "endes123321@gmail.com"

[[menu.main]]
	name   = "Directrices"
	url    = "guidelines/"
	weight = 0

[[menu.main]]
	name   = "Modelo Oembed"
	url    = "oembed-model/"
	weight = 10

[[menu.main]]
	name   = "Elementos polymer"
	url    = "polymer-elements/"
	weight = 20

[[menu.main]]
	name   = "Protocolo FIWA"
	url    = "protocol/"
	weight = 30

[[menu.main]]
	name   = "Protocolo iwa"
	url    = "protocol/iwa"
	weight = 32

[[menu.main]]
	name   = "Protocolos extras"
	url    = "protocol/extras"
	weight = 35

[[menu.main]]
	name   = "Libreria"
	url    = "fiwa-library/"
	weight = 40
[[menu.main]]
	name   = "Creditos"
	url    = "license/"
	weight = 50


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true

[Languages]
